name: 'report'
on:
  workflow_run:
    workflows: [ 'Go' ]
    types:
      - completed
permissions:
  checks: write
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Download Report
        uses: dawidd6/action-download-artifact@v2
        with:
          name: junit-test-results
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: Report
        uses: dorny/test-reporter@v1
        with:
          artifact: go-unit-test-report
          name: Go Tests
          path: '*.xml'
          reporter: jest-junit
